### ISSUE TITLE
Actual integration to sadm

### ISSUE THREAD

**Issue by zopieux** [prologin/dj-ango#2]
setup that works:
- on misc: dj_ango itself, mpd, icecast
- on the remote machine having the jack output: mpv that reads the misc mpd playlist

The observed lag between orders (next, skip, ...) and actual changes: 5 seconds.

**Comment by zopieux** [comment]
What the hell dude, this jack stuff is beyond stupid.

**Comment by natch444** [comment]
Migrated to : https://gitlab.com/prologin/tech/services/dj-ango/-/issues/2
