### ISSUE TITLE
v2 feature list

### ISSUE THREAD

**Issue by zopieux** [prologin/dj-ango#3]
* [ ] **efficient packaging and complete deployment doc**
* [ ] asynchronous (task-based, so downloads are in the background and retries automatically)
* [ ] malus when queuing a song that was already played (based on number of plays and/or time since last play)
* [ ] dictator mode: skip current song, force next song(s) regardless of votes
* [ ] other sources than YouTube (because: censored songs, TV versions with shitty intro, censored results in the search API)
* [ ] in-page audio preview for moderators
* [ ] show original source name (eg. YouTube title) on validation page, so that moderators cannot be tricked with fake artist/title

**Comment by natch444** [comment]
Migrated to https://gitlab.com/prologin/tech/services/dj-ango/-/issues/3
